before:
  hooks:
    - go run ./internal/generate/completions
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - completions/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
brews:
  - homepage: https://github.com/clevyr/kubedb
    description: Painlessly work with Kubernetes databases
    license: GPL-3.0
    repository:
      owner: clevyr
      name: homebrew-tap
    folder: Formula
    install: |
      bin.install "{{ .ProjectName }}"
      bash_completion.install "completions/{{ .ProjectName }}.bash" => "{{ .ProjectName }}"
      zsh_completion.install "completions/{{ .ProjectName }}.zsh" => "_{{ .ProjectName }}"
      fish_completion.install "completions/{{ .ProjectName }}.fish"
dockers:
  - &dockers
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-amd64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
  - <<: *dockers
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-armv7
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"
  - <<: *dockers
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-arm64v8
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - &docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-armv7
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - <<: *docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}
  - <<: *docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:{{ .Major }}
  - <<: *docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
nfpms:
  - id: packages
    vendor: Clevyr
    homepage: https://github.com/clevyr/kubedb
    description: Painlessly work with Kubernetes databases
    license: GPL-3.0
    maintainer: Gabe Cook <gabe@clevyr.com>
    formats:
      - deb
      - rpm
    contents:
      - src: ./completions/{{ .ProjectName }}.bash
        dst: /usr/share/bash-completion/completions/{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./completions/{{ .ProjectName }}.fish
        dst: /usr/share/fish/vendor_completions.d/{{ .ProjectName }}.fish
        file_info:
          mode: 0644
      - src: ./completions/{{ .ProjectName }}.zsh
        dst: /usr/share/zsh/vendor-completions/_{{ .ProjectName }}
        file_info:
          mode: 0644
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -sf -Fpackage=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/clevyr/
