project_name: kubedb
version: 2
before:
  hooks:
    - go mod download
    - go run ./internal/generate/completions
    - go run ./internal/generate/manpages --version={{ .Version }} --date={{ .CommitDate }}
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X k8s.io/client-go/pkg/version.gitVersion=v{{ .Version }}-{{ .Branch }}+{{ .FullCommit }}
      - -X k8s.io/client-go/pkg/version.gitCommit={{ .FullCommit }}
      - -X k8s.io/client-go/pkg/version.gitTreeState={{ if .IsGitDirty }}dirty{{ else }}clean{{ end }}
      - -X k8s.io/client-go/pkg/version.buildDate={{ .CommitDate }}
    tags:
      # Disable Google Cloud Storage GRPC to reduce binary size
      # https://pkg.go.dev/cloud.google.com/go/storage#hdr-gRPC_API
      - disable_grpc_modules
      # Disable GRPC tracing to reduce binary size
      # https://github.com/grpc/grpc-go/blob/master/trace_notrace.go
      - grpcnotrace
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
        goarm: "7"
    mod_timestamp: "{{.CommitTimestamp}}"
archives:
  - formats: tar.gz
    builds_info:
      owner: 0
      group: 0
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - src: LICENSE
        info: &info
          owner: 0
          group: 0
          mtime: "{{.CommitDate}}"
          mode: 0644
      - src: README.md
        info: *info
      - src: manpages/*
        info: *info
      - src: completions/*
        info: *info
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
  groups:
    - title: Features
      order: 0
      regexp: "(feat)"
    - title: Fixes
      order: 1
      regexp: "(fix|perf)"
    - title: Dependencies
      order: 999
      regexp: '\(deps\):'
    - title: Others
      order: 998
brews:
  - homepage: https://github.com/clevyr/kubedb
    description: Painlessly work with Kubernetes databases
    license: GPL-3.0
    repository:
      owner: clevyr
      name: homebrew-tap
    directory: Formula
    install: |
      bin.install "{{ .ProjectName }}"
      man1.install Dir["manpages/*"]
      bash_completion.install Dir["completions/bash/*"]
      zsh_completion.install Dir["completions/zsh/*"]
      fish_completion.install Dir["completions/fish/*"]
dockers:
  - &dockers
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-amd64
    use: buildx
    dockerfile: goreleaser.Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - <<: *dockers
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-armv7
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"
  - <<: *dockers
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-arm64v8
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - &docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-armv7
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - <<: *docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}
  - <<: *docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:{{ .Major }}
  - <<: *docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
nfpms:
  - id: packages
    vendor: Clevyr
    homepage: https://github.com/clevyr/kubedb
    description: Painlessly work with Kubernetes databases
    license: GPL-3.0
    maintainer: Gabe Cook <gabe@clevyr.com>
    formats:
      - deb
      - rpm
    contents:
      - src: ./manpages/
        dst: /usr/share/man/man1
        file_info:
          mode: 0644
      - src: ./completions/bash/
        dst: /usr/share/bash-completion/completions
        file_info:
          mode: 0644
      - src: ./completions/zsh/
        dst: /usr/share/zsh/vendor-completions
        file_info:
          mode: 0644
      - src: ./completions/fish/
        dst: /usr/share/fish/vendor_completions.d
        file_info:
          mode: 0644
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -sf -Fpackage=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/clevyr/
aurs:
  - name: "{{ .ProjectName }}-bin"
    homepage: https://github.com/clevyr/kubedb
    description: Painlessly work with Kubernetes databases
    maintainers:
      - Gabe Cook <gabe565@gmail.com>
    license: GPL-3.0
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: ssh://aur@aur.archlinux.org/{{ .ProjectName }}-bin.git
    skip_upload: auto
    package: |-
      # bin
      install -Dm755 "./{{ .ProjectName }}" "${pkgdir}/usr/bin/{{ .ProjectName }}"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/{{ .ProjectName }}/LICENSE"
      # man pages
      install -Dm644 -t"${pkgdir}/usr/share/man/man1" manpages/*
      # completion
      install -Dm644 -t"${pkgdir}/usr/share/bash-completion/completions" completions/bash/*
      install -Dm644 -t"${pkgdir}/usr/share/zsh/site-functions" completions/zsh/*
      install -Dm644 -t"${pkgdir}/usr/share/fish/vendor_completions.d" completions/fish/*
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
