// Code generated by "stringer -type Format -linecomment"; DO NOT EDIT.

package sqlformat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Gzip-1]
	_ = x[Plain-2]
	_ = x[Custom-3]
}

const _Format_name = "unknowngzipplaincustom"

var _Format_index = [...]uint8{0, 7, 11, 16, 22}

func (i Format) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Format_index)-1 {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[idx]:_Format_index[idx+1]]
}
